language: scala

# ignored, because if we do the ++ thing it uses the wrong
# scalaVersion to compile the sbt plugin which blows up
scala:
- 2.12.7
script:
- sbt test "readme/run --validate"
jdk:
- oraclejdk8
- openjdk11
sudo: false